name: fridge_ai_flutter
description: "FridgeAi"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.9.0
  image_picker: ^1.0.7
  flutter_slidable: ^3.0.1
  package_info: ^2.0.2
  lottie: ^3.1.0
  sqflite: ^2.3.2
  tflite_flutter: ^0.10.4
  image: ^4.1.7
  http: ^1.2.1
  dio: ^5.4.1
  intl: ^0.19.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_auth: ^4.16.0
  provider: ^6.1.2
  go_router: ^13.2.0

dev_dependencies:
  mockito: ^5.0.0
  build_runner:
  test: ^1.24.9
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_driver:
    sdk: flutter

flutter:
  assets:
    - assets/lottie_animations/splash.json
    - assets/model.tflite
    - assets/labels.txt
    - assets/model_MobileNet.tflite
  uses-material-design: true